name: brains
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.7
- pytorch=1.3
- torchvision=0.4.1
- numpy
- pandas
- matplotlib
- pip:
  - pathlib
  - opencv-python
  - Pillow
  - SimpleITK
  - jupyter
  - scikit-image